version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  # Install our python package before building the docs.
  install:
    - method: pip
      path: .[docs]

sphinx:
  configuration: docs/source/conf.py

formats: all
